### ISSUE TITLE
[Request Feature] Add support for Extended Block Shapes "Vertical Slab"

### ISSUE THREAD

**Issue by ardissaps** [CebbysMods/slabref-mod#15]
Would you like to support verticall slab from below mod? Thank you very much for the great mod.

That Mod Making many vanilla missing shape with default texture, could possible mixed slab for their vertical slab.
https://www.curseforge.com/minecraft/mc-mods/extended-block-shapes

Additions :
How about readable name showed at WTHIT? (https://imgur.com/a/yVwO3qw)
Thank you very much.

**Comment by CebbyS** [comment]
Hi, @ardissaps!

That was the plan for this mod future updates, But after some thinking, I have thought about creating another mod, that would implement such functionality. It's better to keep **refabricated slabs** mod simple so that the updates and fixes can be pushed out more quickly.

I tried to implement vertical slabs and their mixing. It felt a bit unpolished, and I don't want to get into a lot of detail. In short, there were a lot of complicated things that needed to be resolved and that is the reason why I will keep that functionality outside of this mod and put it in another one. We will see when.

Thank you for your suggestion!
