### ISSUE TITLE
Minecraft stops with exception when Slabby mod is present

### ISSUE THREAD

**Issue by SnowedInOwl** [CebbysMods/slabref-mod#21]
As of this moment Slabby doesn't work with refabslab i want to use this mod with it so if this could be fixed i would be great

Link to Slabby Below

[https://www.curseforge.com/minecraft/mc-mods/slabby](url)

**Comment by SnowedInOwl** [comment]
I have Made the Mod Maker of Slabby Aware of this too.

**Comment by CebbyS** [comment]
Thanks @SnowedInOwl ! I will take a look!

And my does not work you mean:
- There is some exception and the game shuts down?
- Vertical slabs cant be mixed?

Thanks and regards!

**Comment by SnowedInOwl** [comment]
> Thanks @SnowedInOwl ! I will take a look!
> 
> And my does not work you mean:
> 
> * There is some exception and the game shuts down?
> * Vertical slabs cant be mixed?
> 
> Thanks and regards!

There is some exception and the game shuts down

**Comment by CebbyS** [comment]
Can you please provide the logs from your game to get further details?

**Comment by SnowedInOwl** [comment]
> Can you please provide the logs from your game to get further details?

Here Are Logs You asked for.

[latest.log](https://github.com/CebbysMods/refabslab-mod/files/9183192/latest.log)

[crash-2022-07-25_11.43.31-client.txt](https://github.com/CebbysMods/refabslab-mod/files/9183194/crash-2022-07-25_11.43.31-client.txt)

**Comment by CebbyS** [comment]
Hi, @SnowedInOwl !

To me it seems that Slabby is using old Fabric API that is no longer used in latest versions:
`Caused by: java.lang.NoSuchMethodError:`
`'void net.fabricmc.fabric.impl.content.registry.FlammableBlockRegistryImpl.method_14491(net.minecraft.class_3300)'`

Please provide this message to developer of Slabby mod to fix it. This is not an issue with Refabricated slabs

**Comment by SnowedInOwl** [comment]
Ok
